"""A progressive, bilingual beginner path. No additional client-side scripts."""
from html import escape
from hardware_content import hardware_section
from ha_showcase import home_showcase

SOURCES = {
 'ha':'https://www.home-assistant.io/',
 'alexa':'https://developer.amazon.com/en-US/docs/alexa/smarthome/wwa-connection-options.html',
 'google':'https://support.google.com/googlehome/answer/13127223?hl=pt-BR',
 'apple':'https://support.apple.com/pt-br/102557',
 'samsung':'https://developer.smartthings.com/docs/automations/rules',
 'tuya':'https://developer.tuya.com/en/docs/iot/user-manual-for-tuya-smart-v3177?id=K9obrofrfk4sk',
 'zbt':'https://support.nabucasa.com/hc/en-us/articles/29400591254301',
 'zha':'https://www.home-assistant.io/integrations/zha/',
 'auto':'https://www.home-assistant.io/getting-started/automation/',
}
SCREENS = {
 'dashboard.png':(1701,1299,'https://www.home-assistant.io/getting-started/onboarding_dashboard/'),
 'onboarding.png':(614,575,'https://www.home-assistant.io/getting-started/onboarding/'),
 'imager.png':(860,538,'https://www.home-assistant.io/installation/raspberrypi/'),
 'automation.png':(1021,586,SOURCES['auto']),
 'action.png':(953,330,SOURCES['auto']),
 'integrations.png':(1365,860,'https://www.home-assistant.io/getting-started/integration/'),
 'apps.png':(1138,608,'https://www.home-assistant.io/getting-started/concepts-terminology/'),
 'zbt-discovery.png':(350,230,SOURCES['zbt']),
 'zbt-zigbee.png':(564,317,SOURCES['zbt']),
 'zha-add.png':(684,288,SOURCES['zbt']),
}
def screen(file,caption,lang='pt'):
 w,h,src=SCREENS[file];en=lang=='en'
 author='Nabu Casa' if file.startswith(('zbt','zha')) else 'Home Assistant'
 return f'''<figure class="ha-screen"><a href="/static/img/ha-guide/{file}" target="_blank" rel="noopener" aria-label="{'Enlarge screenshot' if en else 'Ampliar tela'}: {escape(caption)}"><img src="/static/img/ha-guide/{file}" alt="{escape(caption)}" width="{w}" height="{h}" loading="lazy" decoding="async"></a><figcaption>{escape(caption)} <a class="ext" href="{src}" target="_blank" rel="noopener">{'Official screenshot' if en else 'Tela oficial'} · {author}</a> <span>{'In English; labels may vary by version. Click to enlarge.' if en else 'Em inglês; os nomes podem variar por versão. Toque para ampliar.'}</span><a href="/static/img/ha-guide/README.md">{'Image credits' if en else 'Créditos das imagens'}</a></figcaption></figure>'''

# Label, explanation, benefit, limitation, source, English versions.
PLATFORMS=[
 ('Home Assistant','A central que reúne aparelhos e automações de marcas diferentes.','Controle local, liberdade de escolha e automações flexíveis.','Precisa de uma central ligada, configuração inicial e manutenção.','ha',
 'A hub that brings devices and automations from different brands together.','Local control, choice and flexible automations.','Needs an always-on hub, initial setup and maintenance.'),
 ('Alexa','O ecossistema da Amazon, conhecido pelos aparelhos Echo e comandos de voz.','Prático para voz e rotinas simples com aparelhos compatíveis.','Muitas funções dependem da nuvem; rádios e recursos variam entre modelos Echo.','alexa',
 'Amazon’s ecosystem, known for Echo devices and voice commands.','Convenient voice control and simple routines with supported devices.','Many features use the cloud; radios and capabilities vary by Echo model.'),
 ('Google Home','O app e o ecossistema do Google para organizar e controlar a casa.','Reúne controles, voz e dispositivos Matter compatíveis.','Matter exige uma central compatível; acesso remoto e serviços online dependem da internet.','google',
 'Google’s app and ecosystem for organizing and controlling your home.','Combines controls, voice and supported Matter devices.','Matter needs a compatible hub; remote access and online services need internet.'),
 ('Apple Home / HomeKit','O app Casa integra acessórios compatíveis ao iPhone e à Siri.','Boa integração com os aparelhos Apple e automações do app Casa.','Acesso remoto e automações precisam de uma central Apple; confira o suporte do acessório.','apple',
 'The Home app connects supported accessories to iPhone and Siri.','Fits Apple devices and Home app automations.','Remote access and automations need an Apple home hub; check accessory support.'),
 ('Samsung SmartThings','Um app para reunir aparelhos Samsung e de outras marcas compatíveis.','Rotinas gráficas; algumas podem rodar localmente em uma central compatível.','Nem toda rotina é local. Recursos e protocolos dependem dos aparelhos e da central.','samsung',
 'An app for Samsung devices and other supported brands.','Visual routines; some can run locally on a compatible hub.','Not every routine is local. Features and protocols depend on devices and the hub.'),
 ('Tuya / Smart Life','Uma plataforma usada por muitas marcas, geralmente pelo app Smart Life.','Facilita começar pelo celular e oferece aparelhos de várias categorias.','Recursos e qualidade variam por fabricante; muitas funções usam nuvem, embora alguns hubs executem cenas locais.','tuya',
 'A platform used by many brands, often through the Smart Life app.','Easy phone-based setup and many device categories.','Features and quality vary; many functions use the cloud, although some hubs run local scenes.'),
]
def platforms(lang='pt'):
 en=lang=='en';out=[]
 for name,desc,pro,con,source,de,pe,ce in PLATFORMS:
  out.append(f'''<article class="platform-choice{' platform-featured' if source=='ha' else ''}"><p class="eyebrow">{('Our guide’s focus' if en else 'O foco do nosso guia') if source=='ha' else ('Platform' if en else 'Plataforma')}</p><h3>{name}</h3><p>{de if en else desc}</p><dl><dt>{'Advantages' if en else 'Vantagens'}</dt><dd>{pe if en else pro}</dd><dt>{'Limitations' if en else 'Limitações'}</dt><dd>{ce if en else con}</dd></dl><a class="ext" href="{SOURCES[source]}" target="_blank" rel="noopener">{'Official reference' if en else 'Referência oficial'}</a></article>''')
 return '<div class="platform-choices">'+''.join(out)+'</div>'

def beginner_home(lang='pt'):
 en=lang=='en';t=lambda a,b:b if en else a
 def head(num,id,title,desc):return f'<header class="section-head"><p class="eyebrow">{num} / {t("Um passo de cada vez","One step at a time")}</p><h2 id="{id}">{title}</h2><p>{desc}</p></header>'
 def link(url,pt,eng):return f'<a class="btn btn-ghost" href="{url}">{t(pt,eng)} →</a>'
 out=[]
 out.append('<section class="wrap section" aria-labelledby="casa-inteligente">'+head('01','casa-inteligente',t('O que é uma casa inteligente?','What is a smart home?'),t('É uma casa em que aparelhos conectados ajudam nas tarefas do dia a dia. Você pode controlá-los pelo celular, por voz ou deixar uma automação agir por você.','Connected devices help with everyday tasks. Control them by phone or voice, or let an automation act for you.'))+f'''<div class="lesson-examples"><article><h3>{t('Controlar','Control')}</h3><p>{t('Apagar a luz pelo celular, sem levantar do sofá.','Turn off a light from your phone without leaving the sofa.')}</p></article><article><h3>{t('Automatizar','Automate')}</h3><p>{t('Acender a luz do corredor quando alguém passar.','Turn on the hallway light when someone walks by.')}</p></article><article><h3>{t('Acompanhar','Check')}</h3><p>{t('Ver se uma janela ficou aberta antes de sair.','Check whether a window was left open before going out.')}</p></article></div><p class="lesson-note">{t('Comece com uma necessidade, uma luz ou um sensor. Não é preciso automatizar a casa inteira.','Start with one need, one light or one sensor. There is no need to automate the whole house.')}</p></section>''')
 out.append('<section class="lesson-tint"><div class="wrap section">'+head('02','plataformas',t('Qual plataforma organiza tudo isso?','Which platform brings it together?'),t('Estas opções podem coexistir. Aqui, o Home Assistant será a central; os demais sistemas podem complementar a experiência.','These platforms can coexist. Here, Home Assistant is the hub; other systems can complement it.'))+platforms(lang)+f'<p class="lesson-note">{t("Nossa escolha para aprender: Home Assistant OS, com Zigbee local. Ter um aparelho compatível com Alexa ou Smart Life não garante que ele funcione diretamente no Home Assistant: confira o modelo.","Our learning path: Home Assistant OS with local Zigbee. An Alexa or Smart Life badge alone does not guarantee direct Home Assistant support: check the exact model.")}</p></div></section>')
 out.append('<section class="wrap section" aria-labelledby="entenda-ha">'+head('03','entenda-ha',t('Home Assistant: o centro da casa.','Home Assistant: the center of your home.'),t('É um programa gratuito e de código aberto que reúne controles, sensores e automações em uma tela. Ele roda em um aparelho que fica ligado em casa.','Free, open-source software that brings controls, sensors and automations onto one screen. It runs on an always-on device at home.'))+f'''<div class="lesson-split"><div><h3>{t('Você usa botões e menus.','You use buttons and menus.')}</h3><p>{t('A tela mostra luzes, temperatura e outros aparelhos que você adicionar. Para começar, basta aprender a abrir um dispositivo, dar um nome e escolher o cômodo.','The screen shows the lights, temperatures and devices you add. Start by opening a device, naming it and assigning a room.')}</p><p>{t('Com aparelhos e integrações locais, as automações continuam sem internet. A central e a rede precisam permanecer ligadas; serviços de nuvem ainda dependem da internet.','With local devices and integrations, automations work without internet. The hub and local network must stay on; cloud services still need internet.')}</p>{link('/home-assistant/','Entender o Home Assistant','Understand Home Assistant (PT)')}</div>{screen('dashboard.png',t('Exemplo de painel: controles organizados por ambiente.','Example dashboard: controls organized by room.'),lang)}</div>{home_showcase(lang)}</section>''')
 out.append(hardware_section(lang))
 out.append('<section class="lesson-tint"><div class="wrap section">'+head('05','primeiros-passos',t('Comece pelo Home Assistant OS.','Start with Home Assistant OS.'),t('O HAOS é o sistema pronto para cuidar do Home Assistant, das atualizações e dos Apps. É a única instalação da nossa trilha inicial.','HAOS manages Home Assistant, updates and Apps. It is the only installation used in our beginner path.'))+f'''<div class="lesson-examples"><article><h3>{t('1. Escolha a central','1. Choose your hub')}</h3><p>{t('O Green já vem com HAOS. No Raspberry Pi ou mini-PC compatível, siga a instalação pela interface gráfica.','Green comes with HAOS. On a compatible Raspberry Pi or mini PC, follow the graphical installation guide.')}</p></article><article><h3>{t('2. Conecte e abra','2. Connect and open')}</h3><p>{t('Ligue a central à energia e ao roteador por cabo. No navegador, abra','Connect power and Ethernet. In your browser, open')} <code>homeassistant.local:8123</code>.</p></article><article><h3>{t('3. Siga as telas','3. Follow the screens')}</h3><p>{t('Crie sua conta, confira a localização e conheça o painel. Depois, configure um backup.','Create your account, check your location and explore the dashboard. Then set up a backup.')}</p></article></div>{link('/instalar-haos/','Instalar e fazer o primeiro acesso','Install and set up (PT)')}</div></section>''')
 out.append('<section class="wrap section" aria-labelledby="zigbee-inicio">'+head('06','zigbee-inicio',t('Zigbee: nossa primeira rede.','Zigbee: our first network.'),t('Zigbee é uma conexão sem fio para lâmpadas, botões e sensores. Ela usa uma rede própria, sem colocar cada aparelho no seu Wi-Fi.','Zigbee is a wireless connection for lights, buttons and sensors. It uses its own network rather than adding every device to Wi-Fi.'))+f'''<div class="connection-flow"><span>{t('Sensor Zigbee','Zigbee sensor')}</span><b aria-hidden="true">↔</b><strong>ZBT-2 + Home Assistant</strong><b aria-hidden="true">↔</b><span>{t('Luz Zigbee','Zigbee light')}</span></div><div class="lesson-examples protocol-basics"><article class="platform-featured"><h3>{t('Por que começar com Zigbee?','Why start with Zigbee?')}</h3><p>{t('Ampla variedade de aparelhos, baixo consumo para sensores a pilha e controle local com ZHA. Dispositivos compatíveis ligados à energia podem repetir o sinal e ampliar a rede.','A wide device selection, low-power battery sensors and local control through ZHA. Suitable mains-powered devices can relay the signal.')}</p></article><article><h3>{t('O que observar','What to check')}</h3><p>{t('Precisa de um coordenador, como o ZBT-2. Paredes e interferência de 2,4 GHz afetam o sinal. Sensores a pilha geralmente não repetem sinal; confirme a compatibilidade de cada modelo.','Needs a coordinator such as ZBT-2. Walls and 2.4 GHz interference affect reception. Battery sensors usually do not relay signals; check each model’s support.')}</p></article><article><h3>{t('E o Thread?','What about Thread?')}</h3><p>{t('Também cria uma rede de baixo consumo, comum em produtos Matter. Integra-se à rede doméstica por um roteador de borda. É uma opção útil, mas adiciona esse requisito e exige conferir a compatibilidade.','Another low-power network, often used by Matter devices. It connects through a Thread border router. Useful, but it adds that requirement and needs compatibility checks.')}</p></article></div><p class="lesson-note">{t('O ZBT-2 usa Zigbee ou Thread, um por vez. Nesta trilha, vamos mantê-lo em Zigbee.','ZBT-2 uses Zigbee or Thread, one at a time. This path keeps it on Zigbee.')}</p>{link('/zigbee/','Entender o Zigbee','Understand Zigbee (PT)')}</section>''')
 out.append('<section class="wrap section lesson-divider" aria-labelledby="matter-inicio">'+head('07','matter-inicio',t('Matter: marcas falando a mesma língua.','Matter: a shared language for brands.'),t('Matter é um padrão para conectar aparelhos compatíveis a diferentes plataformas. Ele pode usar Wi-Fi, Ethernet ou Thread. Matter e Thread não são a mesma coisa.','Matter is a standard for connecting supported devices to different platforms. It can use Wi-Fi, Ethernet or Thread. Matter and Thread are different things.'))+f'<p class="lesson-note">{t("Vantagem: facilita usar um aparelho em mais de um ecossistema. Limitação: o suporte às funções varia; produtos Matter sobre Thread precisam de um roteador de borda Thread e de um controlador Matter. Você pode começar com Zigbee e explorar Matter depois.","Benefit: it can make one device available to multiple ecosystems. Limitation: feature support varies; Matter-over-Thread devices need a Thread border router and a Matter controller. You can start with Zigbee and explore Matter later.")}</p>'+link('/matter-thread/','Entender Matter e Thread','Understand Matter and Thread (PT)')+'</section>')
 out.append('<section class="lesson-tint"><div class="wrap section">'+head('08','zha-inicio',t('ZBT-2 + ZHA: conecte o primeiro aparelho.','ZBT-2 + ZHA: connect your first device.'),t('O ZBT-2 é o adaptador USB que conversa por Zigbee. O ZHA é a integração que já vem no Home Assistant para gerenciar essa rede.','ZBT-2 is the USB adapter that speaks Zigbee. ZHA is Home Assistant’s built-in integration for managing that network.'))+f'''<div class="lesson-split"><ol class="lesson-steps"><li>{t('Conecte o ZBT-2 à central pelo cabo USB e afaste-o do roteador e de objetos metálicos.','Connect ZBT-2 to the hub with its USB cable, away from your router and metal objects.')}</li><li>{t('Em Configurações → Dispositivos e serviços, adicione o ZBT-2 detectado.','Under Settings → Devices & services, add the discovered ZBT-2.')}</li><li>{t('Escolha “Usar como adaptador Zigbee” e “Instalação recomendada”. O assistente configura o ZHA.','Choose “Use as Zigbee adapter” and “Recommended installation”. The wizard sets up ZHA.')}</li><li>{t('No ZHA, escolha Adicionar dispositivo e coloque a luz ou o sensor em pareamento, conforme o manual.','In ZHA, choose Add device, then put your light or sensor into pairing mode following its manual.')}</li></ol>{screen('zbt-zigbee.png',t('Escolha Zigbee no assistente do ZBT-2.','Choose Zigbee in the ZBT-2 wizard.'),lang)}</div>{link('/zbt-dongles/','Ver o passo a passo com telas','See the illustrated steps (PT)')}<p class="lesson-note">{t('Existe também o Zigbee2MQTT (Z2M), uma alternativa abordada no','Zigbee2MQTT (Z2M) is another option, covered in')} <a href="/aprofundamento/#zigbee2mqtt">{t('aprofundamento','further learning (PT)')}</a>.</p></div></section>''')
 out.append('<section class="wrap section" aria-labelledby="primeira-automacao">'+head('09','primeira-automacao',t('Sua primeira automação, sem código.','Your first automation, without code.'),t('Vamos acender uma luz ao pôr do sol. Você escolhe o que inicia a automação e o que ela deve fazer.','Let’s switch on a light at sunset. Choose what starts the automation and what it does.'))+f'''<div class="lesson-split">{screen('automation.png',t('O editor separa Quando, E se e Então fazer.','The editor separates When, And if and Then do.'),lang)}<div><ol class="lesson-steps"><li>{t('Abra Configurações → Automações e cenas → Criar automação.','Open Settings → Automations & scenes → Create automation.')}</li><li>{t('Em Quando, adicione Sol → Pôr do sol.','Under When, add Sun → Sunset.')}</li><li>{t('Em Então fazer, escolha Luz → Ligar e selecione sua lâmpada.','Under Then do, choose Light → Turn on and select your light.')}</li><li>{t('Salve com um nome, como “Luz ao anoitecer”.','Save it with a name such as “Evening light”.')}</li></ol>{link('/primeira-automacao/','Criar e testar pela interface','Create and test in the UI (PT)')}</div></div></section>''')
 out.append('<section class="lesson-tint"><div class="wrap section">'+head('10','proximos-passos',t('Funcionou? Acrescente uma coisa de cada vez.','Working well? Add one thing at a time.'),t('Esses recursos são opcionais. Não são pré-requisitos para acender sua primeira luz com ZHA.','These features are optional. You do not need them for your first light with ZHA.'))+f'''<div class="next-lessons"><details><summary>1. {t('Integrações: conectar aparelhos','Integrations: connect devices')}</summary><p>{t('São as conexões com marcas e serviços. O ZHA já é uma integração. Você adiciona outras em Configurações → Dispositivos e serviços → Adicionar integração.','These connect brands and services. ZHA is already an integration. Add others under Settings → Devices & services → Add integration.')}</p></details><details><summary>2. Apps (Add-ons): {t('serviços extras','extra services')}</summary><p>{t('São programas adicionais instalados pela loja do HAOS. O ZHA não precisa de MQTT nem de um App extra. Instale um App quando um guia específico pedir.','Extra programs installed through the HAOS app store. ZHA does not need MQTT or an extra App. Install one when a specific guide calls for it.')}</p></details><details><summary>3. HACS: {t('recursos da comunidade','community additions')}</summary><p>{t('É um catálogo da comunidade para integrações e elementos visuais adicionais. Não é a loja de Apps do HAOS. Pode exigir manutenção extra; deixe para quando houver uma necessidade.','A community catalog of extra integrations and dashboard elements. It is different from the HAOS app store and may need extra maintenance. Wait until you have a reason to use it.')}</p></details><details><summary>4. {t('Câmeras: primeiro, ver a imagem','Cameras: start with live view')}</summary><p>{t('Confira a integração do modelo e comece exibindo a imagem no painel. Gravação e detecção por IA são etapas posteriores, com requisitos próprios.','Check your model’s integration and start with live view in your dashboard. Recording and AI detection come later and have their own requirements.')}</p></details></div>{link('/apps-integracoes/','Conhecer os próximos passos','Explore next steps (PT)')}</div></section>''')
 return '\n'.join(out)
