"""Illustrated Home Assistant introduction shared by the bilingual homepage."""
from html import escape
import json
from pathlib import Path

ASSETS = {r['file']: r for r in json.loads((Path(__file__).parent/'static/img/ha-features/sources.json').read_text())}
REF = {
 'integrations':'https://www.home-assistant.io/integrations/',
 'automation':'https://www.home-assistant.io/getting-started/automation/',
 'cloud':'https://www.nabucasa.com/',
 'assist':'https://www.home-assistant.io/voice_control/',
 'voice':'https://www.home-assistant.io/voice-pe/',
 'mobile':'https://companion.home-assistant.io/',
 'apple':'https://www.home-assistant.io/integrations/homekit/',
 'esp32':'https://docs.espressif.com/projects/esp-dev-kits/en/latest/esp32/esp32-devkitc/user_guide.html',
 'atom':'https://docs.m5stack.com/en/core/AtomS3',
 'esp':'https://esphome.io/install/getting-started/',
 'frigate':'https://frigate.video/',
 'faces':'https://docs.frigate.video/configuration/face_recognition/',
 'genai':'https://docs.frigate.video/configuration/genai/genai_objects/',
 'reolink':'https://reolink.com/product/rlc-810a/',
}
# A brand badge is not a compatibility promise: link the actual integration route.
BRANDS = [
 ('LG','webostv','TVs webOS com controle local; eletrodomésticos ThinQ usam outra integração, em nuvem.','Local webOS TV control; ThinQ appliances use a separate cloud integration.'),
 ('Samsung','samsungtv','TVs compatíveis pela rede local; outros aparelhos podem usar SmartThings, em nuvem.','Supported TVs over the local network; other appliances may use cloud-based SmartThings.'),
 ('Tuya / Smart Life','tuya','A integração oficial usa nuvem. Dispositivos Zigbee compatíveis podem entrar direto no ZHA.','The official integration uses the cloud. Supported Zigbee devices can pair directly with ZHA.'),
 ('Aqara','zha','Sensores Zigbee compatíveis pelo ZHA; produtos Matter ou HomeKit seguem outro caminho.','Supported Zigbee sensors through ZHA; Matter and HomeKit products use different routes.'),
 ('Sony','braviatv','TVs Bravia compatíveis: volume, entradas e reprodução, conforme o modelo.','Supported Bravia TVs: volume, inputs and playback, depending on the model.'),
 ('Eve','homekit_controller','Acessórios HomeKit pelo HomeKit Device; versões Matter pela integração Matter.','HomeKit accessories through HomeKit Device; Matter versions through Matter.'),
 ('Tapo / TP-Link','tplink','Tomadas, interruptores, luzes e câmeras suportadas; confira a lista e a autenticação.','Supported plugs, switches, lights and cameras; check the device list and authentication.'),
 ('Reolink','reolink','Vídeo e eventos locais nos modelos suportados; aparelhos a bateria têm requisitos próprios.','Local video and events on supported models; battery devices have additional requirements.'),
 ('Intelbras','onvif','Câmeras com ONVIF Profile S compatível ou fluxo RTSP. Nem toda a linha oferece esses recursos.','Cameras with compatible ONVIF Profile S or RTSP streams. Not every product provides these.'),
 ('Philips Hue','hue','Luzes e cenas locais pela Hue Bridge. Lâmpadas Zigbee compatíveis também podem usar ZHA.','Local lights and scenes through Hue Bridge. Compatible Zigbee bulbs can also use ZHA.'),
 ('Epson','epson','Projetores de rede compatíveis: energia e seleção de entrada para a cena de cinema.','Supported network projectors: power and input selection for a movie scene.'),
]

def ext(url,label):
 return f'<a class="ext" href="{escape(url,quote=True)}" target="_blank" rel="noopener">{label}</a>'

def photo(file,caption,source,lang='pt',product=False):
 r=ASSETS[file];p='/static/img/ha-features/'+file
 return f'''<figure class="feature-figure{' feature-product' if product else ''}"><a href="{p}" target="_blank" rel="noopener" aria-label="{'Enlarge' if lang=='en' else 'Ampliar'}: {escape(caption,quote=True)}"><img src="{p}" width="{r['width']}" height="{r['height']}" alt="{escape(caption,quote=True)}" loading="lazy" decoding="async"></a><figcaption>{caption} · {ext(source,'Official image' if lang=='en' else 'Imagem oficial')}</figcaption></figure>'''

def brand_details(lang='pt'):
 en=lang=='en'
 chips=''.join(f'<a href="https://www.home-assistant.io/integrations/{slug}/" target="_blank" rel="noopener">{name}</a>' for name,slug,pt,eng in BRANDS)
 rows=''.join(f'<li><strong>{name}</strong><span>{eng if en else pt}</span></li>' for name,slug,pt,eng in BRANDS)
 return f'''<div class="ha-brand-list" aria-label="{'Integration examples' if en else 'Exemplos de integrações'}">{chips}</div><details class="feature-details"><summary>{'What can I connect from each brand?' if en else 'O que posso conectar de cada marca?'}</summary><ul class="ha-brand-notes">{rows}</ul><p>{'Check the exact model, firmware and supported features before buying. One integration can support several brands; a brand can use several integrations.' if en else 'Antes de comprar, confira modelo, firmware e funções disponíveis. Uma integração pode atender várias marcas; uma marca pode usar várias integrações.'}</p></details>'''

def home_showcase(lang='pt'):
 en=lang=='en';t=lambda pt,eng:eng if en else pt
 out=[f'''<div class="ha-showcase"><nav class="ha-feature-nav" aria-label="{t('Explore o Home Assistant','Explore Home Assistant')}"><a href="#ha-rotinas">{t('Rotinas','Routines')}</a><a href="#ha-marcas">{t('Marcas','Brands')}</a><a href="#ha-voz">{t('Voz','Voice')}</a><a href="#ha-celular">{t('No celular','On your phone')}</a><a href="#ha-diy">DIY / ESPHome</a><a href="#ha-cameras">{t('Câmeras','Cameras')}</a></nav>
<div class="feature-block"><p class="eyebrow">{t('A casa acompanha você','A home that follows your day')}</p><h3 id="ha-rotinas">{t('Uma ideia. Vários aparelhos. Tudo junto.','One idea. Many devices. Working together.')}</h3>
<div class="ha-scenarios"><article><span>01</span><h4>{t('Bom dia, casa.','Good morning, home.')}</h4><p>{t('No horário escolhido, as cortinas se abrem e a luz aumenta aos poucos. O termostato prepara o conforto do quarto.','At your chosen time, curtains open and lights gently brighten. The thermostat gets your room comfortable.')}</p></article><article><span>02</span><h4>{t('Hoje tem cinema.','Movie night is on.')}</h4><p>{t('Um toque ou uma frase: TV ou projetor ligado, cortinas fechadas e luzes RGBCCT no tom da noite.','One tap or a phrase: TV or projector on, curtains closed and RGBCCT lighting set for the evening.')}</p></article><article><span>03</span><h4>{t('A casa avisa.','Your home keeps you informed.')}</h4><p>{t('Um sensor percebe a janela aberta. A câmera detecta alguém no portão. Você recebe o aviso e decide o que fazer.','A sensor notices an open window. A camera detects someone at the gate. You get a notification and decide what to do.')}</p></article></div>
<p class="feature-small">{t('Exemplos de cenas e automações que você pode criar com dispositivos compatíveis.','Examples of scenes and automations you can build with supported devices.')}</p></div>
<div class="feature-block"><figure class="feature-figure ha-light-photo"><a href="/static/img/devices/hue-liane-2026.jpg" target="_blank" rel="noopener"><img src="/static/img/devices/hue-liane-2026.jpg" width="800" height="450" alt="{t('Iluminação ambiente Philips Hue Liane','Philips Hue Liane ambient lighting')}" loading="lazy" decoding="async"></a><figcaption>{t('Philips Hue Liane: iluminação que participa da decoração.','Philips Hue Liane: lighting as part of your decor.')} · {ext('https://www.signify.com/global/our-company/news/press-releases/2026/20260903-philips-hue-expands-on-smart-lighting-with-ai-immersive-entertainment-and-design','Signify / Philips Hue')}</figcaption></figure><h3>{t('Do interruptor ao ambiente inteiro.','From a switch to an entire room.')}</h3><div class="ha-control-grid">
<article><h4>{t('Luz que muda o clima','Lighting that sets the mood')}</h4><p>{t('Lâmpadas, fitas de LED e luzes RGBCCT: cores RGB, brilho e branco quente ou frio. Crie uma cena para ler, jantar ou relaxar.','Bulbs, LED strips and RGBCCT lights: RGB colors, brightness and warm-to-cool white. Create scenes for reading, dinner or relaxing.')}</p></article>
<article><h4>{t('Conforto sob medida','Comfort your way')}</h4><p>{t('Ar-condicionado, ventiladores, termostatos e cortinas motorizadas. Sensores de presença e temperatura ajudam a agir na hora certa.','Air conditioning, fans, thermostats and motorized blinds. Presence and temperature sensors help them respond at the right time.')}</p></article>
<article><h4>{t('Controle e proteção','Control and awareness')}</h4><p>{t('TVs, projetores, tomadas, interruptores (switches), relés e alarmes. Reúna controles e estados no mesmo painel.','TVs, projectors, plugs, switches, relays and alarms. Bring controls and status together in one dashboard.')}</p></article></div>
<p class="feature-small">{t('Controle pelo painel, por voz, de fora de casa ou por automação. O funcionamento local depende do aparelho e da integração; alguns recursos ainda usam nuvem.','Control from a dashboard, by voice, away from home or through automation. Local operation depends on the device and integration; some features still use the cloud.')}</p></div>
<div class="feature-block"><p class="eyebrow">{t('Liberdade para combinar','Freedom to mix and match')}</p><h3 id="ha-marcas">{t('Suas marcas favoritas podem trabalhar juntas.','Your favorite brands can work together.')}</h3><p>{t('Mais de 1.500 integrações no catálogo oficial conectam aparelhos, marcas e serviços. Uma luz de uma marca pode responder ao sensor de outra, sob as regras que você escolheu.','Over 1,500 integrations in the official catalog connect devices, brands and services. A light from one brand can respond to another brand’s sensor, following your rules.')}</p>{brand_details(lang)}<p class="feature-small">{ext(REF['integrations'],t('Explorar o catálogo oficial','Explore the official catalog'))}</p></div>
<div class="feature-block feature-pair"><div><p class="eyebrow">{t('Automações pelas telas','Automations on screen')}</p><h3>{t('Você escolhe o “quando”. A casa faz o resto.','You choose “when”. Your home does the rest.')}</h3><p>{t('No editor visual, escolha o que inicia a regra, as condições e a ação. Horário, pôr do sol, presença, temperatura ou um evento de câmera podem ser o ponto de partida.','In the visual editor, choose the trigger, conditions and action. A time, sunset, presence, temperature or camera event can be the starting point.')}</p><div class="ha-rule"><span>{t('Quando: alguém passar','When: someone walks by')}</span><span>{t('Se: estiver escuro','If: it is dark')}</span><strong>{t('Então: acender o corredor','Then: light the hallway')}</strong></div><p>{t('Comece com uma regra. Depois, combine aparelhos e aproveite modelos prontos chamados blueprints. Para esse começo, não precisa escrever scripts.','Start with one rule. Later, combine devices and try ready-made templates called blueprints. You do not need scripts for these first steps.')}</p><a class="feature-link" href="/primeira-automacao/">{t('Criar minha primeira automação','Create my first automation (PT)')} →</a></div>
<figure class="feature-figure"><a href="/static/img/ha-guide/automation.png" target="_blank" rel="noopener"><img src="/static/img/ha-guide/automation.png" width="1021" height="586" alt="{t('Editor visual de automações do Home Assistant','Home Assistant visual automation editor')}" loading="lazy" decoding="async"></a><figcaption>{t('Editor visual: Quando, E se e Então fazer. Tela oficial em inglês.','Visual editor: When, And if and Then do. Official screenshot in English.')} · {ext(REF['automation'],'Home Assistant')}</figcaption></figure></div>
<div class="feature-block"><p class="eyebrow">{t('Pode falar com a casa','Talk to your home')}</p><h3 id="ha-voz">{t('“Acenda a sala.” “Ative o cinema.”','“Turn on the living room.” “Movie time.”')}</h3>
<div class="feature-pair"><div><h4>Alexa + Google Nest</h4><p>{t('Continue usando seu Echo ou Google Nest para controlar dispositivos e cenas expostos pelo Home Assistant. A Nabu Casa simplifica essa ponte com Alexa e Google Assistant.','Keep using your Echo or Google Nest to control devices and scenes exposed by Home Assistant. Nabu Casa simplifies the link to Alexa and Google Assistant.')}</p><p>{t('Você escolhe quais controles disponibilizar. Os comandos suportados variam por tipo de aparelho; esses assistentes comerciais precisam de internet.','You choose which controls to expose. Supported commands vary by device type; these commercial assistants need internet.')}</p><h4>{t('Assist: a voz do próprio Home Assistant','Assist: Home Assistant’s own voice')}</h4><p>{t('Use o Assist no celular ou em um dispositivo de voz, como o Voice Preview Edition. Ele pode processar a voz localmente, com hardware e idioma compatíveis, ou usar o Home Assistant Cloud.','Use Assist on your phone or a voice device such as Voice Preview Edition. Speech can be processed locally with suitable hardware and language support, or through Home Assistant Cloud.')}</p><p>{t('Também dá para montar pontos de voz com ESP32 e ESPHome. Escolha uma placa com microfone e alto-falante adequados, como o ATOM Echo.','You can also build voice satellites with ESP32 and ESPHome. Choose suitable microphone and speaker hardware, such as ATOM Echo.')}</p>{ext(REF['assist'],t('Conhecer o Assist','Explore Assist'))}</div>{photo('voice-pe.webp',t('Voice Preview Edition ao lado do Home Assistant Green.','Voice Preview Edition beside Home Assistant Green.'),REF['voice'],lang,True)}</div></div>
<div class="feature-block ha-access-grid"><article><p class="eyebrow">iOS + Android</p><h3 id="ha-celular">{t('A casa vai com você.','Your home goes with you.')}</h3><p>{t('O aplicativo oficial Home Assistant Companion leva o painel ao iPhone, iPad e Android. Veja câmeras, ajuste o ar, feche cortinas e receba notificações.','The official Home Assistant Companion app brings your dashboard to iPhone, iPad and Android. View cameras, adjust cooling, close blinds and receive notifications.')}</p><p>{t('Com permissão, sensores do celular e localização podem participar das automações. Em casa, use a rede local; fora dela, configure Home Assistant Cloud ou uma VPN.','With permission, phone sensors and location can participate in automations. Use the local network at home; configure Home Assistant Cloud or a VPN for access away.')}</p>{ext(REF['mobile'],t('Conhecer os aplicativos','Explore the apps'))}</article>
<article class="ha-cloud-card"><p class="eyebrow">Nabu Casa</p><h3>{t('Menos configuração. Mais casa conectada.','Less setup. More connected living.')}</h3><p>{t('Home Assistant Cloud é a assinatura opcional da Nabu Casa, parceira da Open Home Foundation. Ela facilita o acesso remoto criptografado, sem abrir portas no roteador, e a conexão com Alexa e Google.','Home Assistant Cloud is Nabu Casa’s optional subscription, supporting the Open Home Foundation. It simplifies encrypted remote access without router port forwarding, plus Alexa and Google connections.')}</p><p>{t('Inclui backup na nuvem e processamento de voz para o Assist. Também ajuda a financiar Home Assistant e ESPHome. A assinatura não é necessária para automações locais.','It includes cloud backup and speech processing for Assist, while helping fund Home Assistant and ESPHome. Local automations do not require a subscription.')}</p><a class="feature-link" href="/nabu-casa/">{t('Entender as vantagens da Nabu Casa','Explore Nabu Casa benefits (PT)')} →</a></article></div>
<div class="feature-block ha-apple"><p class="eyebrow">Apple Home / HomeKit</p><h3>{t('Gosta do app Casa? Pode continuar com ele.','Like Apple Home? Keep using it.')}</h3><p>{t('O ecossistema da Apple é mais fechado e tem regras próprias para acessórios. A integração HomeKit Bridge leva controles compatíveis do Home Assistant ao app Casa e à Siri — inclusive de aparelhos que não oferecem HomeKit nativo.','Apple’s ecosystem is more closed, with its own accessory requirements. HomeKit Bridge brings supported Home Assistant controls into Apple Home and Siri, including devices without native HomeKit support.')}</p><p>{t('Você escolhe o que compartilhar. Nem toda função pode ser espelhada. Acesso remoto pelo app Casa exige uma central Apple compatível, como HomePod ou Apple TV; Matter amplia as opções de acessórios.','You choose what to share. Not every function can be bridged. Remote access through Apple Home needs a suitable Apple hub, such as HomePod or Apple TV; Matter broadens accessory choice.')}</p><a class="feature-link" href="/apple-homekit/">{t('Conectar ao app Casa pelas telas','Connect to Apple Home on screen (PT)')} →</a></div>
<div class="feature-block"><p class="eyebrow">IoT + DIY</p><h3 id="ha-diy">{t('Sua ideia pode virar um dispositivo.','Your idea can become a device.')}</h3><p>{t('IoT é a internet das coisas: objetos conectados trocando informações. DIY é fazer você mesmo. Com placas ESP32 e ESPHome, crie sensores, botões, pequenos painéis e controles feitos para a sua casa.','IoT means connected objects exchanging information. DIY means do it yourself. With ESP32 boards and ESPHome, build sensors, buttons, small displays and controls tailored to your home.')}</p>
<div class="ha-diy-photos">{photo('esp32.webp',t('ESP32-DevKitC: uma placa de desenvolvimento de uso geral.','ESP32-DevKitC: a general-purpose development board.'),REF['esp32'],lang,True)}{photo('atom-s3.webp',t('M5Stack ATOM-S3: ESP32-S3, tela e botão em um módulo compacto.','M5Stack ATOM-S3: ESP32-S3, display and button in a compact module.'),REF['atom'],lang,True)}</div>
<div class="feature-pair"><div><h4>{t('ESPHome: começar ficou mais fácil','ESPHome makes getting started easier')}</h4><p>{t('Projeto da Open Home Foundation apoiado pela Nabu Casa, o ESPHome tem o App Device Builder no HAOS. Um assistente cria a base; você instala pelo USB e pode atualizar depois por Wi-Fi.','ESPHome is an Open Home Foundation project supported by Nabu Casa. Its Device Builder App runs in HAOS. A wizard creates the initial setup; install over USB and update later over Wi-Fi.')}</p><p>{t('Projetos prontos encurtam o caminho. Para personalizar sensores e telas, costuma-se editar uma configuração YAML, sem escrever um programa em C++. Uma IA pode explicar, rascunhar e ajudar a corrigir essa configuração.','Ready-made projects shorten the path. Custom sensors and displays usually need YAML configuration rather than a C++ program. AI can explain, draft and help debug that configuration.')}</p><p class="feature-small">{t('Confira modelo, pinos e documentação; valide antes de gravar. Comece com USB e baixa tensão. O ATOM-S3 mostrado não é um assistente de voz completo: áudio exige hardware próprio.','Check the board, pins and documentation; validate before flashing. Start with USB and low voltage. The pictured ATOM-S3 is not a complete voice assistant: audio needs suitable hardware.')}</p><a class="feature-link" href="/esphome-esp32/">{t('Descobrir o ESPHome','Discover ESPHome (PT)')} →</a></div>{photo('esphome-builder.webp',t('Device Builder: seus projetos organizados em cartões.','Device Builder: projects organized into cards.'),REF['esp'],lang)}</div></div>
<div class="feature-block"><p class="eyebrow">{t('Câmeras + inteligência artificial','Cameras + artificial intelligence')}</p><h3 id="ha-cameras">{t('Veja o que acontece. Receba o que importa.','See what happens. Get the updates that matter.')}</h3><p>{t('Comece vendo a câmera no painel. Depois, um NVR — sistema que organiza e grava vídeos — como o Frigate pode separar pessoas, carros e animais e transformar eventos em avisos ou automações.','Start with a camera in your dashboard. Later, an NVR — a system for recording and organizing video — such as Frigate can distinguish people, cars and animals and turn events into notifications or automations.')}</p>
<div class="feature-pair ha-nvr-pair">{photo('frigate-live.webp',t('Frigate NVR: câmeras reunidas em uma tela.','Frigate NVR: cameras together on one screen.'),REF['frigate'],lang)}{photo('reolink.webp',t('Reolink RLC-810A: exemplo de câmera de rede PoE.','Reolink RLC-810A: a PoE network camera example.'),REF['reolink'],lang,True)}</div>
<div class="ha-control-grid"><article><h4>{t('Detectar','Detect')}</h4><p>{t('Uma pessoa entrou na zona do portão? Acenda a luz e envie uma foto. Os objetos detectáveis dependem do modelo de IA.','Someone entered the gate zone? Turn on the light and send a photo. Detectable objects depend on the AI model.')}</p></article><article><h4>{t('Reconhecer rostos','Recognize faces')}</h4><p>{t('O Frigate pode comparar rostos com uma biblioteca cadastrada, usando processamento local e hardware compatível. É um recurso adicional, sujeito a erros.','Frigate can match faces against an enrolled library using local processing and compatible hardware. It is an optional feature and can make mistakes.')}</p></article><article><h4>{t('Descrever ações','Describe actions')}</h4><p>{t('Modelos de visão podem descrever cenas, como alguém deixando uma caixa. Podem rodar localmente ou na nuvem, conforme o provedor; as descrições precisam de contexto e podem falhar.','Vision models can describe scenes, such as someone leaving a parcel. They can run locally or in the cloud depending on the provider; descriptions need context and may be wrong.')}</p></article></div>
<p class="feature-small">{t('Gravação e IA pedem armazenamento e processamento próprios; não vêm prontas em qualquer central. Use reconhecimento como apoio a avisos, não como único critério para destrancar portas ou desarmar alarmes.','Recording and AI need suitable storage and processing; they are not ready to run on every hub. Use recognition to support notifications, not as the sole reason to unlock doors or disarm alarms.')}</p><a class="feature-link" href="/cameras-ia/">{t('Explorar câmeras e IA, aos poucos','Explore cameras and AI step by step (PT)')} →</a></div>
<div class="feature-block ha-next"><h3>{t('Uma boa casa inteligente começa pequena.','A great smart home starts small.')}</h3><p>{t('Zigbee e Thread são ótimos para sensores a pilha: baixo consumo e rede em malha, em que aparelhos adequados ajudam a levar o sinal mais longe. Zigbee será nosso primeiro passo com ZHA e ZBT-2.','Zigbee and Thread suit battery sensors: low power and mesh networking, where suitable devices relay the signal. Zigbee with ZHA and ZBT-2 will be our first step.')}</p><p>{t('Eles não substituem tudo: Wi-Fi e Ethernet continuam ideais para vídeo e tráfego maior. Vamos explicar as diferenças mais adiante. Agora, escolha sua central e dê vida à primeira automação.','They do not replace everything: Wi-Fi and Ethernet remain well suited to video and higher data rates. We explain the differences later. Now choose your hub and bring your first automation to life.')}</p><a class="btn btn-primary" href="#hardware-haos">{t('Quero começar: escolher minha central','Get started: choose my hub')} →</a><p class="feature-small"><a href="/home-assistant/">{t('Ler o guia completo do Home Assistant','Read the full Home Assistant guide (PT)')}</a> · <a href="/static/img/ha-features/README.md">{t('Créditos das imagens','Image credits')}</a></p></div>
</div>''']
 return '\n'.join(out)
